baseURL = 'https://goddesscameo.github.io/'
languageCode = 'en-us'
title = 'GoddessCameo - CONFIG FIXED'
theme = ['github.com/CaiJimmy/hugo-theme-stack/v3']

[module]
[[module.imports]]
path = 'github.com/CaiJimmy/hugo-theme-stack/v3'
